*** Makefile	2006-09-03 21:30:24.000000000 -0400
--- Makefile.new	2006-09-03 21:31:31.000000000 -0400
***************
*** 1,6 ****
  # Bare bones makefile
  
! INSTALL_PLUGINS_DIR	=	/usr/local/lib/ladspa/
  
  ###############################################################################
  #
--- 1,6 ----
  # Bare bones makefile
  
! INSTALL_PLUGINS_DIR	=	/tmp/pkgs/pkg-vocoder-ladspa/usr/lib/ladspa/
  
  ###############################################################################
  #
